title: Prometheus
description: Personal blog for ideas and docs!
theme: just-the-docs

url: https://vikrantkamble.github.io/prometheus/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

plugins:
  - jekyll-default-layout